import os
import streamlit as st
from langchain_ollama import OllamaLLM, OllamaEmbeddings
from langchain_community.vectorstores import Chroma

CONSTITUTION = """
You are සිංහල සහායකයා — a Sinhala AI assistant. You must strictly follow these rules on every response:

1. LANGUAGE: Always respond in Sinhala Unicode script only. Never mix English words or letters into your response. Every single word must be in Sinhala Unicode.
2. NO TRANSLITERATION: STRICTLY FORBIDDEN — never add romanized text or brackets after Sinhala. Do NOT write "(Kolamba.)" or "(Ayubowan)" — this is a critical rule violation.
3. SAFETY: Never provide harmful, violent, illegal, or unethical advice under any circumstances.
4. HONESTY: If you genuinely do not know the answer, say "මට මේ ගැන තොරතුරු නැත." Never fabricate facts or invent words.
5. TONE: Always maintain a respectful, neutral, and polite tone.
6. GROUNDING: If relevant context is provided, use it to answer. For general knowledge questions where no context is available, use your training knowledge to give a correct Sinhala answer.
7. UNICODE: Always write Sinhala in proper Unicode only — never in Singlish or Latin script.
8. VOCABULARY: Only use real, commonly known Sinhala words. If you do not know the correct Sinhala word, use a simpler known word instead of inventing one.
9. NO BRACKETS: Never use brackets () to add translations, explanations, or romanized text after any Sinhala sentence.
"""

@st.cache_resource
def load_llm():
    """Load the SinGemma model via Ollama local server."""
    return OllamaLLM(model="Tharusha_Dilhara_Jayadeera/singemma", temperature=0.3)

@st.cache_resource
def load_retriever():
    """
    Load the ChromaDB vector store for RAG retrieval.
    Returns None gracefully if no knowledge base has been ingested yet.
    This allows the chatbot to work even without documents loaded.
    """
    embeddings = OllamaEmbeddings(model="nomic-embed-text")
    if os.path.exists("./chroma_db"):
        vectorstore = Chroma(
            persist_directory="./chroma_db",
            embedding_function=embeddings
        )
        # k=3 means: fetch the 3 most relevant document chunks.
        # More chunks = more context but slower & noisier responses.
        return vectorstore.as_retriever(search_kwargs={"k": 3})
    return None  # No documents ingested yet — chatbot still works

llm = load_llm()
retriever = load_retriever()

def build_prompt(user_input: str, context: str = "", history: str = "") -> str:
    """
    Constructs the full prompt sent to the LLM.
    Order matters: Constitution → Context → History → Question.
    """
    return f"""{CONSTITUTION}

### Knowledge Base Context (use this to answer):
{context if context else "No specific context available. Use general knowledge but stay within rules."}

### Recent Conversation History:
{history if history else "This is the start of the conversation."}

### User's Question:
{user_input}

### Your Sinhala Response:"""


def get_rag_context(query: str) -> str:
    """
    Queries ChromaDB to find document chunks most similar to the user's question.
    Uses cosine similarity on embeddings generated by nomic-embed-text.
    Returns an empty string if no retriever is loaded.
    """
    if retriever:
        docs = retriever.invoke(query)
        # Join the top-k document chunks into a single context block
        return "\n\n".join([doc.page_content for doc in docs])
    return ""


def build_history(messages: list) -> str:
    """
    Converts the last 6 session messages into a readable conversation string.
    This gives the LLM short-term memory within the session.
    """
    recent = messages[-6:]  # Only last 6 messages to stay within context limits
    history = ""
    for msg in recent:
        role = "පරිශීලකයා" if msg["role"] == "user" else "සහායකයා"
        history += f"{role}: {msg['content']}\n"
    return history

# 
# STREAMLIT UI
#

st.set_page_config(
    page_title="හෙළයා",
    page_icon="🤖",
    layout="centered"
)

st.title("🤖 සිංහල AI චැට්බොට්")
st.caption("🔒 Fully Offline | ⚖️ Constitutional AI | 📚 RAG-Powered | ⚡ Streaming")

# Sidebar: 
with st.sidebar:
    st.header("⚙️ System Status")

    # LLM loaded correctly
    st.success("✅ හෙළයා loaded")

    # whether RAG knowledge base is available
    if retriever:
        st.success("✅ Knowledge base active")
    else:
        st.warning("⚠️ No knowledge base.\nAdd PDFs to /documents\nthen run: python ingest.py")

    st.divider()
    st.header("⚖️ Active Constitution")
    st.info(CONSTITUTION)

# Session State Initialisation 
# First run: messages list doesn't exist yet - create it empty.
# Subsequent runs: this block is skipped, preserving history.
if "messages" not in st.session_state:
    st.session_state.messages = []

# Clear Chat Button 
if st.button("🗑️ Clear Chat"):
    st.session_state.messages = []
    st.rerun()

# Render Existing Chat History 
# Loop through all stored messages and render them as chat bubbles.
# st.chat_message("user") renders a human bubble,
# st.chat_message("assistant") renders a bot bubble.
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# Chat Input + Response Pipeline 
# st.chat_input renders the input box pinned to the bottom.
# The walrus operator (:=) assigns AND checks in one line —
# the block only runs when the user actually submits a message.
if user_input := st.chat_input("සිංහලෙන් ටයිප් කරන්න..."):

    # Store and immediately display the user's message
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    # Build all prompt components
    context = get_rag_context(user_input)           # RAG retrieval
    history = build_history(st.session_state.messages[:-1])  # exclude current msg
    full_prompt = build_prompt(user_input, context, history)  # stitch together

    # Stream the response token by token
    with st.chat_message("assistant"):
        response_placeholder = st.empty()
        full_response = ""

        for token in llm.stream(full_prompt):
            full_response += token
            response_placeholder.markdown(full_response + "▌")  # live cursor

        response_placeholder.markdown(full_response)  # final clean render

    # Save the completed response to session history
    st.session_state.messages.append({"role": "assistant", "content": full_response})
